services:
    app:
        build: .
        restart: always
        ports:
            - "9000:80" # Port to access the application from the browser
        volumes:
            - .:/var/www/html # Mount local application folder to container
            - /var/www/html/storage # Storage for Laravel's storage folder
            - /var/www/html/bootstrap/cache # Storage for Laravel's cache
        networks:
            - app_network
        mem_limit: "2G"
        cpus: "1"
        depends_on:
            mysql:
                condition: service_healthy
        environment:
           - APP_ENV=development
           - DB_CONNECTION=mysql
           - DB_HOST=mysql
           - DB_PORT=3306
           - DB_DATABASE=getal_html
           - DB_USERNAME=laravel_user
           - DB_PASSWORD=IADlltyujish1n



    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_DATABASE: getal_html
            MYSQL_ROOT_PASSWORD: IADlltyujish1n
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: IADlltyujish1n
        ports:
            - "3307:3306" # Port to access MySQL
        volumes:
            - db_data:/var/lib/mysql # MySQL data storage
        networks:
            - app_network
        mem_limit: "2G"
        cpus: "1"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pIADlltyujish1n"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db_data:

networks:
    app_network:
        driver: bridge
