#name
name: Deploy G et al app to Azure

#trigger
on:
  push:
    branches:
      - main

# the actual actions
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, curl, pdo_mysql, bcmath, zip, gd, intl

      - name: Set Laravel Environment Variables in Azure
        run: |
          az webapp config appsettings set --resource-group laravelResourceGroup \
            --name web-laravel \
            --settings \
              APP_ENV=production \
              APP_DEBUG=false \
              APP_KEY=${{ secrets.APP_KEY }} \
              DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              BROADCAST_CONNECTION=ably \
              QUEUE_CONNECTION=database \
              SESSION_DRIVER=database \
              SESSION_LIFETIME=120 \
              SESSION_ENCRYPT=false \
              SESSION_PATH=/ \
              SESSION_DOMAIN=null \
              FILESYSTEM_DISK=local \
              AZURE_STORAGE_NAME=${{ secrets.AZURE_STORAGE_NAME }} \
              AZURE_STORAGE_KEY=${{ secrets.AZURE_STORAGE_KEY }} \
              AZURE_CONTAINER=laravel-files

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: web-laravel
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Install composer Dependencies
        run: |
          composer install --optimize-autoloader
          php artisan cache:clear
          php artisan config:clear
          php artisan storage:link

      - name: Install npm Dependencies
        run: |
          npm install
          npm run build

