#name
name: PROD Deploy G et al app to Azure

#trigger
on:
  push:
    branches:
     - main
    #  - dev

# the actual actions
jobs:
  build-and-deploy:
    name: Build and Deploy web app to Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, json, curl, pdo_mysql, bcmath, zip, gd, intl

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "composer.json"

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Generate autoload files
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer dump-autoload --optimize

      # This will only work if you have a database setup
      - name: Optimize views n routes etc
        if: steps.check_files.outputs.files_exists == 'true'
        run: php artisan route:clear && php artisan view:clear && php artisan config:clear

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install NPM dependencies
        run: npm install

      # Run Vite build
      - name: Build Vite Assets
        run: npm run build

      # Upload Build Artifacts (Optional)
      - name: Upload Vite Build Output
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: public/build/ # Laravel Vite output directory

      - name: Generate Azure App Settings JSON
        run: |
          cat <<EOF > appsettings.json
          {
            "ABLY_KEY": "${{ secrets.ABLY_KEY }}",
            "AI_MAIN_FUNC_URL": "https://mediguides-dev-main-func.azurewebsites.net/api/function",
            "AUTH0_AUDIENCE": "${{ secrets.PROD_AUTH0_AUDIENCE }}",
            "AUTH0_DOMAIN": "${{ secrets.PROD_AUTH0_DOMAIN }}",
            "AUTH0_CLIENT_ID": "${{ secrets.PROD_AUTH0_CLIENT_ID }}",
            "AUTH0_CLIENT_SECRET": "${{ secrets.PROD_AUTH0_CLIENT_SECRET }}",
            "AUTH0_REDIRECT_URI": "https://mediguides-prod.azurewebsites.net/login/auth0/callback",
            "AUTH0_TOKEN_URI":"/oauth/token",
            "APP_ENV": "production",
            "APP_DEBUG": "true",
            "APP_KEY": "${{ secrets.PROD_APP_KEY }}",
            "APP_URL": "https://mediguides-prod.azurewebsites.net/",
            "APP_MAINTENANCE_DRIVER": "file",
            "APP_LOCALE": "en",
            "APP_FALLBACK_LOCALE": "en",
            "APP_FAKER_LOCALE": "en_US",
            "AZURE_STORAGE_NAME": "${{ secrets.PROD_AZURE_STORAGE_NAME }}",
            "AZURE_STORAGE_KEY": "${{ secrets.PROD_AZURE_STORAGE_KEY }}",
            "AZURE_STORAGE_CONNECTION_STRING": "${{ secrets.PROD_AZURE_STORAGE_CONNECTION_STRING }}",
            "AZURE_STORAGE_CONTAINER_NAME": "mediguide-prod-files",
            "AZURE_CONTAINER": "laravel-files",
            "AZURE_STORAGE_URL": "https://mediguidesprodstorage.blob.core.windows.net/mediguide-prod-files",
            "BCRYPT_ROUNDS": "12",
            "BROADCAST_CONNECTION": "ably",
            "PHP_CLI_SERVER_WORKERS": "4",
            "LOG_CHANNEL": "stack",
            "LOG_STACK": "single",
            "LOG_DEPRECATIONS_CHANNEL": "null",
            "LOG_LEVEL": "debug",
            "FILESYSTEM_DISK": "local",
            "QUEUE_CONNECTION": "database",
            "CACHE_STORE": "database",
            "CACHE_PREFIX": "",
            "DB_CONNECTION": "mysql",
            "DB_HOST": "${{ secrets.PROD_DB_HOST }}",
            "DB_PORT": "3306",
            "DB_DATABASE": "${{ secrets.PROD_DB_DATABASE }}",
            "DB_USERNAME": "${{ secrets.PROD_DB_USERNAME }}",
            "DB_PASSWORD": "${{ secrets.PROD_DB_PASSWORD }}",
            "DB_SSL_MODE": "require",
            "DB_SSL_CA":"/home/site/certs/BaltimoreCyberTrustRoot.crt.pem",
            "SESSION_DRIVER": "database",
            "SESSION_LIFETIME": "120",
            "SESSION_ENCRYPT": "false",
            "SESSION_PATH": "/",
            "SESSION_DOMAIN": "",
            "CAIRO_URL":"https://mediguides-dev-svg2png.azurewebsites.net/api/convert",
            "SVG_PROCESS_URL":"https://mediguides-dev-process-svg.azurewebsites.net/api/process",
            "PHP_INI_SCAN_DIR":":/home/site/config/php",
            "PHP_CLI_SERVER_WORKERS":"5",
            "WEBSITES_ENABLE_APP_SERVICE_STORAGE":"true",
            "WEBSITE_CONTENTOVERVNET":"1",
            "WEBJOBS_ENABLED":"1",
            "WEBSITE_SKIP_RUNNING_KUDUAGENT":"false",
            "WEBSITE_VNET_ROUTE_ALL":"1",
            "VITE_APP_URL":"https://mediguides-prod.azurewebsites.net/",
            "JWT_SECRET":"${{ secrets.JWT_SECRET }}"
          }
          EOF

      - name: Set PROD Laravel Environment Variables in Azure
        run: |
          az webapp config appsettings set --resource-group MediGuides_prod_ResourceGroup \
          --name mediguides-prod --settings @appsettings.json

      - name: PROD Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: mediguides-prod
          publish-profile: ${{ secrets.PROD_AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

